#!/bin/bash
# Generate version info with UTC timestamp + incremental build number
TIMESTAMP=$(date -u +"%Y%m%d-%H%M%S")
BUILD_FILE="src/generated-version.ts"
cat > "$BUILD_FILE" << EOF
// Auto-generated by scripts/gen-version.sh — do not edit
export const APP_VERSION = {
  build: '${TIMESTAMP}',
  label: 'build-${TIMESTAMP}',
};
EOF
echo "Version: build-${TIMESTAMP}"
